/**
 * generated-files.ts
 *
 * Creates and manages files generated by AÏKO agents.
 *
 * Security:
 *   - Storage is restricted to storage/generated-files/ under project root.
 *   - Path traversal prevented: all resolved paths must start with STORAGE_BASE.
 *   - File IDs are UUIDs — no user-controlled path segments.
 *   - Content is never read back into AI prompts (CEO cannot read raw file content).
 *   - API keys and secrets are never written to files.
 */

import { db } from '@/lib/db/client'
import fs from 'fs/promises'
import path from 'path'

// ── Storage base ───────────────────────────────────────────────────────────────

const STORAGE_BASE = path.resolve(process.cwd(), 'storage', 'generated-files')

/** Ensure storage root exists. Called lazily before first write. */
async function ensureStorageBase(): Promise<void> {
  await fs.mkdir(STORAGE_BASE, { recursive: true })
}

/**
 * Build a safe absolute storage path for {id}/{filename}.
 * Throws if the resolved path would escape STORAGE_BASE (path traversal guard).
 */
function safePath(id: string, filename: string): string {
  // Sanitize filename: strip path separators and leading dots
  const safeFilename = path.basename(filename).replace(/^\.+/, '_')
  const resolved = path.resolve(STORAGE_BASE, id, safeFilename)
  if (!resolved.startsWith(STORAGE_BASE + path.sep) && resolved !== STORAGE_BASE) {
    throw new Error(`Path traversal detected: ${resolved}`)
  }
  return resolved
}

// ── Types ──────────────────────────────────────────────────────────────────────

export type FileContentType = 'markdown' | 'csv' | 'json' | 'text'

export interface GeneratedFile {
  id:                 string
  project_id:         string | null
  filename:           string
  mime_type:          string
  content_type:       FileContentType
  title:              string | null
  description:        string | null
  generated_by_role:  string | null
  storage_path:       string
  size_bytes:         number
  created_at:         string
}

export interface CreateGeneratedFileInput {
  project_id?:        string | null
  filename:           string
  content:            string
  content_type:       FileContentType
  mime_type?:         string
  title?:             string | null
  description?:       string | null
  generated_by_role?: string | null
}

// ── MIME types ─────────────────────────────────────────────────────────────────

const MIME: Record<FileContentType, string> = {
  markdown: 'text/markdown',
  csv:      'text/csv',
  json:     'application/json',
  text:     'text/plain',
}

// ── Core CRUD ──────────────────────────────────────────────────────────────────

/**
 * Write content to disk and record metadata in the DB.
 */
export async function createGeneratedFile(
  input: CreateGeneratedFileInput
): Promise<GeneratedFile> {
  await ensureStorageBase()

  // Create a UUID-based directory first (to get the id)
  const idRes = await db.query(
    `INSERT INTO generated_files
       (project_id, filename, mime_type, content_type, title, description, generated_by_role, storage_path, size_bytes)
     VALUES ($1,$2,$3,$4,$5,$6,$7,'__placeholder__',0)
     RETURNING id`,
    [
      input.project_id ?? null,
      path.basename(input.filename).replace(/^\.+/, '_'),
      input.mime_type ?? MIME[input.content_type],
      input.content_type,
      input.title ?? null,
      input.description ?? null,
      input.generated_by_role ?? null,
    ]
  )
  const id = idRes.rows[0].id

  // Write file to disk
  const absPath = safePath(id, input.filename)
  await fs.mkdir(path.dirname(absPath), { recursive: true })
  await fs.writeFile(absPath, input.content, 'utf-8')
  const stats  = await fs.stat(absPath)
  const relPath = `generated-files/${id}/${path.basename(absPath)}`

  // Update DB with real path and size
  await db.query(
    `UPDATE generated_files SET storage_path=$1, size_bytes=$2 WHERE id=$3`,
    [relPath, stats.size, id]
  )

  const row = await db.query(
    `SELECT * FROM generated_files WHERE id=$1`, [id]
  )
  return row.rows[0]
}

export async function getGeneratedFile(id: string): Promise<GeneratedFile | null> {
  const res = await db.query(
    `SELECT * FROM generated_files WHERE id=$1`, [id]
  )
  return res.rows[0] ?? null
}

export interface ListGeneratedFilesFilter {
  project_id?: string
  limit?:      number
  offset?:     number
}

export async function listGeneratedFiles(
  filter: ListGeneratedFilesFilter = {}
): Promise<GeneratedFile[]> {
  const conditions: string[] = []
  const params: unknown[]    = []

  if (filter.project_id) {
    params.push(filter.project_id)
    conditions.push(`project_id = $${params.length}`)
  }

  const where  = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : ''
  const limit  = filter.limit  ?? 50
  const offset = filter.offset ?? 0
  params.push(limit, offset)

  const res = await db.query(
    `SELECT * FROM generated_files ${where}
     ORDER BY created_at DESC
     LIMIT $${params.length - 1} OFFSET $${params.length}`,
    params
  )
  return res.rows
}

/**
 * Read raw file content from disk.
 * Returns null if file not found on disk (DB record may still exist).
 */
export async function readGeneratedFileContent(
  file: GeneratedFile
): Promise<Buffer | null> {
  try {
    const absPath = path.resolve(path.join(process.cwd(), 'storage'), file.storage_path)
    // Path traversal guard
    const storageRoot = path.resolve(process.cwd(), 'storage')
    if (!absPath.startsWith(storageRoot + path.sep)) {
      throw new Error('Path traversal detected')
    }
    return await fs.readFile(absPath)
  } catch {
    return null
  }
}

export async function deleteGeneratedFile(id: string): Promise<void> {
  const file = await getGeneratedFile(id)
  if (!file) return

  // Delete from disk
  try {
    const absPath = path.resolve(path.join(process.cwd(), 'storage'), file.storage_path)
    const storageRoot = path.resolve(process.cwd(), 'storage')
    if (absPath.startsWith(storageRoot + path.sep)) {
      await fs.unlink(absPath)
      // Remove parent dir if empty
      await fs.rmdir(path.dirname(absPath)).catch(() => {})
    }
  } catch { /* non-fatal */ }

  await db.query(`DELETE FROM generated_files WHERE id=$1`, [id])
}

// ── Convenience generators ─────────────────────────────────────────────────────

/** Generate a Markdown file and save it. */
export async function generateMarkdownFile(
  projectId: string | null,
  filename:  string,
  title:     string,
  content:   string,
  opts?: { description?: string; role?: string }
): Promise<GeneratedFile> {
  const safeFilename = filename.endsWith('.md') ? filename : `${filename}.md`
  return createGeneratedFile({
    project_id:         projectId,
    filename:           safeFilename,
    content,
    content_type:       'markdown',
    title,
    description:        opts?.description ?? null,
    generated_by_role:  opts?.role ?? null,
  })
}

/** Generate a JSON file and save it. */
export async function generateJsonFile(
  projectId: string | null,
  filename:  string,
  title:     string,
  data:      unknown,
  opts?: { description?: string; role?: string }
): Promise<GeneratedFile> {
  const safeFilename = filename.endsWith('.json') ? filename : `${filename}.json`
  // Stringify with indentation, but never include secrets
  const content = JSON.stringify(data, null, 2)
  return createGeneratedFile({
    project_id:         projectId,
    filename:           safeFilename,
    content,
    content_type:       'json',
    title,
    description:        opts?.description ?? null,
    generated_by_role:  opts?.role ?? null,
  })
}

/** Generate a CSV file and save it. */
export async function generateCsvFile(
  projectId: string | null,
  filename:  string,
  title:     string,
  columns:   string[],
  rows:      (string | number | null)[][],
  opts?: { description?: string; role?: string }
): Promise<GeneratedFile> {
  const safeFilename = filename.endsWith('.csv') ? filename : `${filename}.csv`

  function escapeCell(v: string | number | null): string {
    if (v === null || v === undefined) return ''
    const s = String(v)
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
      return `"${s.replace(/"/g, '""')}"`
    }
    return s
  }

  const header  = columns.map(escapeCell).join(',')
  const body    = rows.map(r => r.map(escapeCell).join(',')).join('\n')
  const content = `${header}\n${body}`

  return createGeneratedFile({
    project_id:         projectId,
    filename:           safeFilename,
    content,
    content_type:       'csv',
    title,
    description:        opts?.description ?? null,
    generated_by_role:  opts?.role ?? null,
  })
}
