/**
 * report-file-export.ts
 *
 * Export executive project reports to downloadable generated files.
 *
 * Safety:
 * - Read-only on DB (reads report, writes generated file record + disk).
 * - Never exposes secrets, API keys, or tokens.
 * - Never writes outside storage/generated-files/.
 * - Never overwrites an existing export for the same report+format unless
 *   allowOverwrite is explicitly true.
 * - The JSON export is structured data only — no raw AI prompt context.
 * - Screenshots are not included.
 */

import { db } from '@/lib/db/client'
import { createGeneratedFile, type GeneratedFile } from '@/lib/generated-files'
import {
  type ExecutiveReport,
  type StrategySnapshot,
  type ProgressSnapshot,
  type DecisionSnapshotItem,
} from '@/lib/project-executive-report'

// ── Public API ────────────────────────────────────────────────────────────────

export type ExportFormat = 'markdown' | 'json'

export interface ExportResult {
  file:         GeneratedFile
  download_url: string
  already_existed: boolean
}

/**
 * Export an executive report to a generated file.
 *
 * @param projectId     The project the report belongs to (ownership check).
 * @param report        The full ExecutiveReport object.
 * @param format        'markdown' | 'json'
 * @param allowOverwrite  If false (default), returns the existing export if one exists.
 */
export async function exportExecutiveReport(
  projectId:      string,
  report:         ExecutiveReport,
  format:         ExportFormat,
  allowOverwrite  = false,
): Promise<ExportResult> {
  // Ownership check — report must belong to the given project
  if (report.project_id !== projectId) {
    const err = new Error('Report does not belong to this project') as Error & { statusCode: number }
    err.statusCode = 404
    throw err
  }

  // Check for an existing export for this report+format
  if (!allowOverwrite) {
    const existing = await findExistingExport(report.id, format)
    if (existing) {
      return {
        file:            existing,
        download_url:    `/api/files/${existing.id}/download`,
        already_existed: true,
      }
    }
  }

  const date = new Date(report.created_at).toISOString().slice(0, 10)  // YYYY-MM-DD
  const slug  = slugify(report.title)

  let file: GeneratedFile

  if (format === 'markdown') {
    const content  = formatExecutiveReportMarkdown(report)
    const filename = `${slug}-${date}.md`
    file = await createGeneratedFile({
      project_id:         projectId,
      filename,
      content,
      content_type:       'markdown',
      title:              `${report.title} (Markdown)`,
      description:        `Markdown export of executive report generated ${date}.`,
      generated_by_role:  report.generated_by_role,
      source_entity_type: 'executive_report',
      source_entity_id:   report.id,
    })
  } else {
    const data     = formatExecutiveReportJson(report)
    const content  = JSON.stringify(data, null, 2)
    const filename = `${slug}-${date}.json`
    file = await createGeneratedFile({
      project_id:         projectId,
      filename,
      content,
      content_type:       'json',
      title:              `${report.title} (JSON)`,
      description:        `JSON export of executive report generated ${date}.`,
      generated_by_role:  report.generated_by_role,
      source_entity_type: 'executive_report',
      source_entity_id:   report.id,
    })
  }

  return {
    file,
    download_url:    `/api/files/${file.id}/download`,
    already_existed: false,
  }
}

// ── Formatters ────────────────────────────────────────────────────────────────

/**
 * Render an ExecutiveReport as a Markdown document.
 * No secrets, no API keys, no screenshots.
 */
export function formatExecutiveReportMarkdown(report: ExecutiveReport): string {
  const date = new Date(report.created_at).toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
  })
  const s = report.strategy_snapshot
  const p = report.progress_snapshot

  const lines: string[] = []

  lines.push(`# ${report.title}`)
  lines.push(``)
  lines.push(`**Generated:** ${date}  `)
  lines.push(`**Generated by:** ${report.generated_by_role}`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  // Executive Summary
  if (report.summary) {
    lines.push(`## Executive Summary`)
    lines.push(``)
    lines.push(report.summary)
    lines.push(``)
  }

  // Strategy
  const hasStrategy = s.goal || s.objective || s.target_audience || s.channel || s.value_prop || s.operator || s.pm
  if (hasStrategy) {
    lines.push(`## Strategy Snapshot`)
    lines.push(``)
    if (s.goal)            lines.push(`- **Goal:** ${s.goal}`)
    if (s.objective)       lines.push(`- **Objective:** ${s.objective}`)
    if (s.target_audience) lines.push(`- **Target Audience:** ${s.target_audience}`)
    if (s.channel)         lines.push(`- **Channel:** ${s.channel}`)
    if (s.value_prop)      lines.push(`- **Value Proposition:** ${s.value_prop}`)
    if (s.operator)        lines.push(`- **Operator:** ${s.operator}`)
    if (s.pm)              lines.push(`- **Project Manager:** ${s.pm}`)
    lines.push(``)
  }

  // Progress
  lines.push(`## Progress Snapshot`)
  lines.push(``)
  if (p.launch_total > 0) {
    const pct = Math.round((p.launch_done / p.launch_total) * 100)
    lines.push(`- **Launch Plan:** ${p.launch_done}/${p.launch_total} steps (${pct}%)${p.launch_status ? ` — ${p.launch_status}` : ''}`)
  }
  lines.push(`- **Leads:** ${p.lead_total} total — ${p.lead_approved} approved, ${p.lead_contacted} contacted, ${p.lead_replied} replied`)
  if (p.pending_approvals > 0) {
    lines.push(`- **Pending Approvals:** ${p.pending_approvals}`)
  }
  lines.push(``)

  // Recent decisions
  if (report.decisions_snapshot.length > 0) {
    lines.push(`## Recent Decisions`)
    lines.push(``)
    for (const d of report.decisions_snapshot) {
      const dDate = new Date(d.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
      lines.push(`### ${d.title}`)
      lines.push(``)
      lines.push(`*${d.decision_type} · ${dDate}*`)
      if (d.summary) {
        lines.push(``)
        lines.push(d.summary)
      }
      lines.push(``)
    }
  }

  // Risks
  if (report.risks.length > 0) {
    lines.push(`## Risks / Blockers`)
    lines.push(``)
    for (const r of report.risks) {
      lines.push(`- ⚠ ${r}`)
    }
    lines.push(``)
  }

  // Next steps
  if (report.next_steps.length > 0) {
    lines.push(`## Recommended Next Steps`)
    lines.push(``)
    for (const s of report.next_steps) {
      lines.push(`- ${s}`)
    }
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(``)
  lines.push(`*This report was generated by AÏKO and is for internal use only.*`)

  return lines.join('\n')
}

/**
 * Render an ExecutiveReport as a structured JSON object.
 * Strips nothing — the report itself contains no secrets.
 * The project_id is included to allow cross-referencing.
 */
export function formatExecutiveReportJson(report: ExecutiveReport): object {
  return {
    id:          report.id,
    project_id:  report.project_id,
    title:       report.title,
    generated_at: report.created_at,
    generated_by: report.generated_by_role,
    summary:     report.summary,
    strategy: {
      goal:            report.strategy_snapshot.goal,
      objective:       report.strategy_snapshot.objective,
      target_audience: report.strategy_snapshot.target_audience,
      channel:         report.strategy_snapshot.channel,
      value_prop:      report.strategy_snapshot.value_prop,
      operator:        report.strategy_snapshot.operator,
      project_manager: report.strategy_snapshot.pm,
    },
    progress: {
      launch_steps_done:   report.progress_snapshot.launch_done,
      launch_steps_total:  report.progress_snapshot.launch_total,
      launch_status:       report.progress_snapshot.launch_status,
      leads_total:         report.progress_snapshot.lead_total,
      leads_approved:      report.progress_snapshot.lead_approved,
      leads_contacted:     report.progress_snapshot.lead_contacted,
      leads_replied:       report.progress_snapshot.lead_replied,
      pending_approvals:   report.progress_snapshot.pending_approvals,
    },
    recent_decisions: report.decisions_snapshot.map(d => ({
      type:       d.decision_type,
      title:      d.title,
      summary:    d.summary,
      created_at: d.created_at,
    })),
    risks:       report.risks,
    next_steps:  report.next_steps,
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function findExistingExport(
  reportId: string,
  format:   ExportFormat,
): Promise<GeneratedFile | null> {
  const contentType = format === 'markdown' ? 'markdown' : 'json'
  try {
    const res = await db.query(
      `SELECT * FROM generated_files
       WHERE source_entity_type = 'executive_report'
         AND source_entity_id   = $1
         AND content_type       = $2
       ORDER BY created_at DESC
       LIMIT 1`,
      [reportId, contentType]
    )
    return res.rows[0] ?? null
  } catch {
    // Migration not yet applied — treat as no existing export
    return null
  }
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 60)
}
