-- Migration 031: project strategy briefs
-- Auto-generated by the CEO when a new project is created.
-- Guidance only — does not trigger any automation or external actions.

CREATE TABLE IF NOT EXISTS project_strategy_briefs (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id           UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title                TEXT NOT NULL DEFAULT '',
  objective            TEXT NOT NULL DEFAULT '',
  target_audience      TEXT NOT NULL DEFAULT '',
  research_prompt      TEXT NOT NULL DEFAULT '',
  recommended_channel  TEXT NOT NULL DEFAULT 'email',
  value_proposition    TEXT NOT NULL DEFAULT '',
  risks                JSONB NOT NULL DEFAULT '[]',
  assumptions          JSONB NOT NULL DEFAULT '[]',
  next_actions         JSONB NOT NULL DEFAULT '[]',
  created_by_role      TEXT NOT NULL DEFAULT 'CEO',
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One active brief per project (idempotent insert guard)
CREATE UNIQUE INDEX IF NOT EXISTS idx_psb_project
  ON project_strategy_briefs (project_id);

CREATE INDEX IF NOT EXISTS idx_psb_project_created
  ON project_strategy_briefs (project_id, created_at DESC);
