-- Migration 035: Generated files
-- Stores metadata for files generated by AÏKO agents.
-- File content is stored on disk under storage/generated-files/{id}/{filename}.

CREATE TABLE IF NOT EXISTS generated_files (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id      UUID        REFERENCES projects(id) ON DELETE SET NULL,
  filename        TEXT        NOT NULL,
  mime_type       TEXT        NOT NULL DEFAULT 'text/plain',
  content_type    TEXT        NOT NULL DEFAULT 'text',  -- markdown | csv | json | text
  title           TEXT,
  description     TEXT,
  generated_by_role TEXT,
  storage_path    TEXT        NOT NULL UNIQUE,           -- relative: generated-files/{id}/{filename}
  size_bytes      INT         NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_generated_files_project_id
  ON generated_files (project_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_generated_files_created_at
  ON generated_files (created_at DESC);
