-- 045_ai_research_strategy_skills.sql
-- Internal AI research, strategy, productivity, and analysis skills.
-- These skills use saved context and user-provided text only. They do not
-- browse, create Web Operator actions, send, post, or publish.

INSERT INTO ai_skills
  (skill_id, name, category, description, input_schema, output_schema, safety_level, enabled)
VALUES
  ('create_marketing_strategy', 'Create Marketing Strategy', 'research_strategy', 'Create a marketing strategy from project context and user-provided information.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_7_day_plan', 'Create 7-Day Plan', 'research_strategy', 'Turn project context into a practical seven-day marketing work plan.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_customer_persona', 'Create Customer Persona', 'research_strategy', 'Create a customer persona from project context or supplied notes.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_competitor_research_plan', 'Create Competitor Research Plan', 'research_strategy', 'Create a competitor research framework and browser research questions.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_market_research_brief', 'Create Market Research Brief', 'research_strategy', 'Create a market research brief from existing context and assumptions.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_positioning_statement', 'Create Positioning Statement', 'research_strategy', 'Create clear positioning and messaging from project context.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_offer', 'Create Offer', 'research_strategy', 'Create a campaign offer from audience, value proposition, and constraints.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_campaign_brief', 'Create Campaign Brief', 'research_strategy', 'Create a campaign brief for internal execution planning.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('analyze_strategy', 'Analyze Strategy', 'research_strategy', 'Review a strategy for clarity, feasibility, risks, and gaps.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('identify_missing_capabilities', 'Identify Missing Capabilities', 'research_strategy', 'Identify missing agents, skills, playbooks, tools, and approval gates.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_task_list', 'Create Task List', 'productivity', 'Convert a plan or request into an internal task list.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_project_plan', 'Create Project Plan', 'productivity', 'Create a project plan from objective, constraints, and known context.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_checklist', 'Create Checklist', 'productivity', 'Create a concise checklist for a workflow or campaign.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_meeting_notes', 'Create Meeting Notes', 'productivity', 'Turn notes or transcript text into concise meeting notes.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('create_decision_summary', 'Create Decision Summary', 'productivity', 'Summarize decisions, rationale, and next actions from provided context.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('summarize_project_status', 'Summarize Project Status', 'analysis', 'Summarize current project status from internal project context.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('analyze_risks', 'Analyze Risks', 'analysis', 'Analyze project, campaign, or execution risks from known context.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('recommend_next_step', 'Recommend Next Step', 'analysis', 'Recommend the next best internal action from project context.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true),
  ('compare_options', 'Compare Options', 'analysis', 'Compare options and recommend a practical path from available context.', '{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string"},"project_id":{"type":"string"}}}', '{"type":"object","properties":{"summary":{"type":"string"},"sections":{"type":"array"},"recommendations":{"type":"array"},"next_actions":{"type":"array"},"needs_web_research":{"type":"boolean"}}}', 'internal_planning_only', true)
ON CONFLICT (skill_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  input_schema = EXCLUDED.input_schema,
  output_schema = EXCLUDED.output_schema,
  safety_level = EXCLUDED.safety_level,
  enabled = EXCLUDED.enabled,
  updated_at = NOW();
